import { useQuery } from '@tanstack/react-query'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { data } = useQuery(['test'], () => fetch('/api/hello').then(r => r.json()))
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {JSON.stringify(data)}
      </main>
    </div>
  )
}

